version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ponguser
      POSTGRES_PASSWORD: pongpassword
      POSTGRES_DB: pongdb

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
