# Generated by Django 3.2.25 on 2024-04-15 16:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(default='pass', max_length=100)),
                ('activity', models.CharField(choices=[('ON', 'Online 🟢'), ('IG', 'In game 🟣'), ('OF', 'Offline 🔴'), ('UN', 'Unavailable 🟡')], default='OF', max_length=2)),
                ('avatar', models.ImageField(blank=True, default=user.models.User.random_avatar_path, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry_time', models.DateTimeField(blank=True, null=True)),
                ('is_oauth', models.BooleanField(default=False)),
                ('twoFA', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', '🇬🇧'), ('fr', '🇫🇷'), ('es', '🇪🇸')], default='en', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_groups', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_permissions', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
