# Generated by Django 3.2.24 on 2024-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/avatars/default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
