# Generated by Django 3.2.25 on 2024-03-19 18:53

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=user.models.User.random_avatar_path, null=True, upload_to='avatars/'),
        ),
    ]
