# Generated by Django 3.2.25 on 2024-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', '🇬🇧'), ('fr', '🇫🇷'), ('es', '🇪🇸')], default='en', max_length=2),
        ),
    ]
