# Generated by Django 3.2.24 on 2024-02-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
