# Generated by Django 3.2.25 on 2024-04-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('ON', 'Online 🟢'), ('IG', 'In game 🟣'), ('OF', 'Offline 🔴')], default='OF', max_length=2),
        ),
    ]
