# Generated by Django 3.2.24 on 2024-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_userbase_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='JohnDoe', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twoFA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='changeYourPasswordASAP', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ON', 'En ligne'), ('IG', 'En partie'), ('OF', 'Hors ligne'), ('UN', 'Indisponible')], default='OF', max_length=2),
        ),
    ]
