# Generated by Django 3.2.25 on 2024-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('ON', 'Online 🟢'), ('IG', 'In game 🟣'), ('OF', 'Offline 🔴'), ('UN', 'Unavailable 🟡')], default='OF', max_length=2),
        ),
    ]
