# Generated by Django 3.2.24 on 2024-02-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20240219_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='activity',
        ),
    ]
