# Generated by Django 3.2.25 on 2024-05-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_history', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('NORM', 'Normal'), ('RMBL', 'Rumble'), ('TOUR', 'Tournament')], max_length=10),
        ),
    ]
