# Generated by Django 3.2.25 on 2024-05-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_history', '0005_alter_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('NORM', 'Normal'), ('RMBL', 'Rumble'), ('TOUR', 'Tournois')], max_length=10),
        ),
    ]
